### ISSUE TITLE
Plugin stops arranging layers when there are rasters or OpenLayers loaded

### ISSUE THREAD

**Issue by amsantac** [abhijitgujar86/QGIS-Layer-arranger#4]
Nice plugin. Great idea. Thanks for your work. I found the following issue:

The plugin stops arranging layers when there are rasters or OpenLayers loaded. See below. Could this be fixed?

2016-04-21T14:00:18 1   Traceback (most recent call last):
              File "C:/Users/Guest/.qgis2/python/plugins\Layer_arranger\layer_arranger.py", line 196, in run
                if layer.geometryType() == QGis.Point:
            AttributeError: 'QgsRasterLayer' object has no attribute 'geometryType'

2016-04-21T14:01:08 1   Traceback (most recent call last):
              File "C:/Users/Guest/.qgis2/python/plugins\Layer_arranger\layer_arranger.py", line 196, in run
                if layer.geometryType() == QGis.Point:
            AttributeError: 'OpenlayersLayer' object has no attribute 'geometryType'

**Comment by abhijitgujar86** [comment]
i looked up for it found this documents will try it and update the plugin . thanks :)

document: https://qgis.org/api/classQGis.html

**Comment by amsantac** [comment]
Great! Thanks for contributing to QGIS community
